ansible_user: USERNAME
ansible_ssh_private_key_file: PATH
ansible_become_password: PASSWORD

docker_secrets:
  db_username: USERNAME
  db_password: PASSWORD
  jwt_secret: SECRET

swarm_user_group: swarm
opt_stack_directory: simple
stack_file: docker-stack.yml

stack_name: simple

docker_registry_url: docker.io # Docker hub
docker_registry_username: USER
docker_registry_password: PASSWORD
